# see https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
globalArguments: []
additionalArguments:
  # If you have all the range ips from OVH you can specify ranges (see README) if not just use insecure
  - "--entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32"
  #- "--entryPoints.web.proxyProtocol.insecure"
  - "--entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32"
  #- "--entryPoints.websecure.proxyProtocol.insecure"

service:
  annotations:
    service.beta.kubernetes.io/ovh-loadbalancer-proxy-protocol: v1
  spec:
    externalTrafficPolicy: Local
